eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 9442
spring:
  application:
    name: user-client
  zipkin:
    base-url: http://localhost:9441
  sleuth:
    sampler:
      percentage: 1.0