eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 9443
spring:
  application:
    name: gate-way
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9441
zuul:
  routes:
    api-gateway:
      path: /user-api/**
      service-id: user-client
