server:
  port: 8772

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /${management.contextPath}/health
        health-check-interval: 15s
        instance-id: consul
  application:
    name: consul
