server:
  port: 8761

spring:
  profiles:
    active: peer1
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8760/eureka/